name: Update Runners

# **What it does**: Close issues and pull requests after no updates for 365 days.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  schedule:
    #- cron: '00 20 * * *' # Run every day at 20:00 UTC / 18:00 CET

jobs:
  update-runner:
    runs-on: [self-hosted, linux]
    steps:
      - name: apt-update
        uses: shell
        with:
          SSH_TOKEN: ${{secrets.SSH_TOKEN}}