name: Check Markdown links

# **What it does**: Check if a link is not working.
# **Why we have it**: We want to make sure all links are valid.
# **Who does it impact**: Everyone.

on: push

jobs:
  markdown-link-check:
    runs-on: "self-hosted"
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
